hydren-crypto/stampchain

.gitignore
asset.html
index.html
style.css

move the stylesheet out of index. title case the stampchain data. prep for the asset page

chore: convert to stylesheet

---

asset.html
index.html

Some stylish updates

---

asset.html

Reverts hydren-crypto/stampchain#9

Revert "feat: add xchain data"

---

asset.html
index.html
minting.html

Addition of Menu

---

asset.html

the variables weren't passing through properly - they were getting overwritten by the counterparty data.

fix:  asset URL's

---

asset.html
index.html
minting.html

Updating the titles and meta data to better align the project. This was actually a recommendation from Adam McBride and it seems reasonable. "STAMPCHAIN" may come across as a shitcoin. I think the domain is fine, but updating the titles is a good idea.
I've also added an iOS meta thumbnail so that if you add it to your favorites or homescreen, it has an icon.

STAMPCHAIN.IO ---> BITCOIN STAMPS

---

buildspec.yml
mint/app.js
mint/index.html

CP trx does not support bech58 otherwise we get Not a valid Base58 character: '0'

chore: bech32 address verification

---

mint/app.js
mint/app_dev.js
mint/index.html
mint/index_dev.html

Hydren dev/fix btcaddycheck

---

mint/app.js
mint/app_dev.js

clear the please wait on failure

chore: move to production endpoint

---

mint/app.js
mint/app_dev.js
mint/index.html
mint/index_dev.html

new addition to the form for testing

chore: add creator / collection to dev page

---

style.css

More cohesive appearance by removing the lower radials so the <pre> items stack.

Small update to fix the radial corner of the pre

---

asset.html
index.html
minting.html

At Jdog's request I've modified the existing STAMPS paper to reflect the broader protocol rules supported by xchain. I've made a duplicate of the paper specific to our project. I've updated the references in the menu accordingly.

Updated link to the Bitcoin Stamps paper

---

mint/index.html
style.css

Adding rules to main stylesheet in root
Changed the css reference to point at main stylesheet in root.

Styling the "mint" page

---

mint/app_dev.js
mint/index_dev.html

testing the artist and collection fields

chore: collection names, lock, etc

---

mint/app.js
mint/index.html

add a simple verification check on the beginning chars

chore: validate address entry

---

app.js
index.html
style.css

add the CP asset search url string, and the searchbox on the front page. also fixing the top and bottom pagination

Hydren dev/asset search

---

index.html
style.css

also needed to touch the html of the index.html to move the copyright notice below the search box.

styling the new search box

---

index.html
mint/index.html

chore: wording on mint page, top search

---

documentation/api.md

cleanup output keys and add the creator key

Hydren dev/creator

---

app.js

This PR:
* points to the newly created API instead of the JSON file
* fixes the funnily reversed < Next and Previous > buttons

chore(app.js): point to API instead of JSON file

---

style.css

There is no space below the pagination buttons which looks ugly. Just added a bit of space.

Update style.css - tiny change

---

docs/src20.md
src20/index.html

new SRC-20 specifications for block height 796000

Hydren dev/new spec

---

docs/api-src20.md
docs/api.md

new queries enabled for src-20 in preparation of new protocol standards

chore: new SRC api backend and queries

---

app.js
asset.html
buildspec.yml
index.html
style.css

cleanup css, style the buttons to be consistent, and add the filters

feat: add filters to sort by src-20, 721, etc

---

app.js
asset.html
index.html

allow html to display in sandboxed iframe

feat: add iframe for html content

---

app.js
asset.html
style.css

still lots of potential cleanup in CSS. working better on mobile now at least

chore: asset-page responsiveness

---

docs/src20.md

fix(src20): cleanup readme specs formatting

---

app.js

chore: update to v2 api
